macOS: Fix macOS 27 os_log compile errors, improve TRACE_VSYNC
Suppress `-Wignored-attributes` triggered when compiling macOS-specific
logging and vsync tracing code.

In the macOS 27 SDK that's part of Xcode 27, Apple appears to have added
an `OS_LOG_UNINITIALIZED` macro inside their logging and signposting
headers (`os/log.h`, `os/signpost.h`, `os/trace_base.h`). This macro
expands to include: `__attribute__((stack_protector_ignore))`.

Because of this, we skip stack protection checks on local formatting
buffers generated by logging macros such as `os_log_with_type` and
`os_signpost_event_emit`. However, in Flutter, we compile the engine
with `-fstack-protector-all`, which causes the build to error out
complaining the `stack_protector_ignore` attribute is being ignored:

  error: 'stack_protector_ignore' attribute ignored due to '-fstack-protector-all' option [-Werror,-Wignored-attributes]

This wraps these usages in ignore pragmas to avoid disabling it across
the board, which is the same as the approach that was taken in:
* https://github.com/dart-lang/sdk/commit/6bea1b7321870ddcccdf5274563b64977a115e5b
* https://github.com/google/angle/commit/918b93f4c0f145b82871a6c515dce8ed90e7d6e0

This also creates the vsync log once and caches it statically as Apple
recommends. `os_log` is already multi-tenant safe.