Update instructions to add option to install via RubyGems
I ran into an issue with the Homebrew install because I was using a Ruby version manager...

```❯ pod setup
dyld: lazy symbol binding failed: Symbol not found: _rb_str_new_static
  Referenced from: /Users/jared/.gem/ruby/2.4.1/gems/json-2.1.0/lib/json/ext/generator.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_str_new_static
  Referenced from: /Users/jared/.gem/ruby/2.4.1/gems/json-2.1.0/lib/json/ext/generator.bundle
  Expected in: flat namespace

[1]    39800 abort      pod setup```

Suggesting updating instructions to add installation via RubyGems. This is also the officially recommended way to install CocoaPods.