[Impeller] Assign missing user to TODO. (flutter/engine#43351)
The linter is failing on this in my unrelated PR for some reason: https://github.com/flutter/engine/pull/43348

```
â Failures for clang-tidy on /Volumes/Work/s/w/ir/cache/builder/src/flutter/impeller/renderer/backend/metal/vertex_descriptor_mtl.mm:
/Volumes/Work/s/w/ir/cache/builder/src/flutter/impeller/renderer/backend/metal/vertex_descriptor_mtl.mm:177:3: error: missing username/bug in TODO [google-readability-todo,-warnings-as-errors]
  // TODO: its odd that we offset buffers from the max index on metal
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // TODO(chrome-bot): its odd that we offset buffers from the max index on metal
Suppressed 1476 warnings (1475 in non-user code, 1 NOLINT).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
1 warning treated as error
```