Add missing import (flutter/engine#47083)
Fixes the following:

https://github.com/flutter/engine/commit/46f9b99627f45c49b30d6470083da29a1ba3f04c results in the following error appearing internally when compiling for Android:

```
In file included from fml/synchronization/sync_switch.cc:5:
./fml/synchronization/sync_switch.h:74:34: error: implicit instantiation of undefined template 'std::vector<fml::SyncSwitch::Observer *>'
  mutable std::vector<Observer*> observers_;
                                 ^
<...>: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
1 error generated.
```

*List which issues are fixed by this PR. You must list at least one issue.*
b/306266542

[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style