flutter_tools/version: git log.showSignature=false
If the site Git configuration has log.showSignature=true, which is not
the default, it will break versioning functions with

  FormatException: FormatException: Invalid date format

This fix forces log.showSignature=false for git log calls in
package:flutter_tools/src/version.dart.

Fixes #38572.