Roll src/third_party/dart 1577b95c93..dbe80f3397 (43 commits)
dbe80f3397 Add tests for late and final variables without an initializer
797e288796 Clarify how ParameterElement getters behave in the presence of `required`.
974babb5f1 Remove named argument `nnbd` from summary testing methods.
f3d8b420a0 Consolidate all NNBD enables in summary_common.dart.
c38b65d2bc Use FreshTypeParameters from type_algebra with summary2.
f931d0e5ab Read bounds of function type type parameters.
836c04f3d2 [vm/compiler] Ensure aliasing between *[C|S] and X[C'|S'] for S < S'.
fb7137ba6f Fix isAbstract when MethodDeclaration is lazy.
f9b68f72f4 Fix copy-paste error with optionalNamed.
0130ffed1b [vm/compiler] Check for errors when loading test scripts.
8866165950 [dartdevc] Reify bottom as Null
c14496a9ee [infra] Prevent front end unit tests from being approved.
102f4addda Include the static type in the receiver type of dynamic invoke
03776172c1 Read VariableDeclaration type during checking for implicitly typed.
d5eba9b77d Remove error if a final field without initializer is marked as late
5393ce7d35 [vm, service] Fix parameter handling for profiler timeline RPCs.
97122d162e Separate abi versions out from create_sdk into their own target.
a43d36cdd9 Support for '===' and '!==' tokens.
ff0f2a6b2e Refactoring renaming of some tests in move_file_test.dart and sorting of the tests
0586be25a4 Read partOf directive metadata lazily.
0950a540d7 Convert summary_common.dart to triple-slash comment style
14d548f239 Add a toString() method for FeatureSet
e25aefc8d6 Consolidate all NNBD enables in resynthesize_common.dart.
48a7e24e39 Store lineStarts with units.
70e00c9a37 Handle ClassTypeAlias without valid Function.
b8fb787994 Add a test for uses of the default List constructor
a334395edf Switch to using FeatureSet in summary tests
dd1ae4c2d8 Fix the order during building library scopes.
4a31d8b62b Additional tests in move_file_test.dart - the analysis server tests for the MOVE_FILE refactoring.
9df061524f [tests] Update expected error NoSuchMethodError --> Error
6819a4db02 test_matrix.json changes for ABI tests
482c36d9ae [vm/debugger] Remove script soucre look up in debugger
98f67ff3d4 [dart/fuzzer] Mechanism for target functions
3646be6fb5 Add a previously missed test and cleanup test names
36b2520ca9 Add a test of creating a subtype of Never
ded5c3efd5 [ VM / Service ] Fixed HTTP requests with params not working correctly when auth codes are enabled
946c38d881 Build local elements for variable initializers.
5bac4d9b0c Reland "Add support for recording context information with analysis errors, with one example"
158a52ee3f Change the message for FLUTTER_REMOVE_WIDGET.
40a06c3a77 Implement the type Never
4fd9312586 Convert session.dart to triple-slash comment style
af4bc38490 Fix for building named function types.
6ac709a2d0 Infer mixin type arguments.