Revert "Migrate all Python scripts to Python 3 (#464)" (#465)
This uncovered some python3 incompatibility in depot_tools:

```
Traceback (most recent call last):
  File "C:\b\s\w\ir\kitchen-checkout\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 608, in <module>
    sys.exit(main())
  File "C:\b\s\w\ir\kitchen-checkout\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 579, in main
    data_json = json.dumps(data)
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
Traceback (most recent call last):
  File "src/build/vs_toolchain.py", line 557, in <module>
    sys.exit(main())
  File "src/build/vs_toolchain.py", line 553, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "src/build/vs_toolchain.py", line 501, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\b\\s\\w\\ir\\cipd_bin_packages\\cpython3\\bin\\python3.exe', 'C:\\b\\s\\w\\ir\\kitchen-checkout\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'C:\\b\\s\\w\\ir\\cache\\builder\\src\\build\\win_toolchain.json', '418b3076791776573a815eb298c8aa590307af63']' returned non-zero exit status 1.
Error: Command 'python3 src/build/vs_toolchain.py update' returned non-zero exit status 1 in C:\b\s\w\ir\cache\builder
Hook 'python3 src/build/vs_toolchain.py update' took 67.10 secs
```

This reverts commit 607277f54052acd038edb4fe4c2f57fd81d96baf.