Add missing import for malloc (#56781)
Internal bug: b/380745221

The use of `malloc` in L70:

https://github.com/flutter/engine/blob/ce1eb371eafa791d3d25e5a031bfc47885859c4d/third_party/tonic/filesystem/filesystem/file.cc#L70

Results in the following error, after an update to the internal toolchain. For some reason, this error only appears when targeting Linux.

```
tonic/filesystem/filesystem/file.cc:70:28: error: use of undeclared identifier 'malloc'
   70 |   uint8_t* ptr = (uint8_t*)malloc(file_size);
      |                            ^
1 error generated.
```

This PR fixes it by including the header file.

[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style