[Docs] RouteObserver<PageRoute> cannot subscribe ModalRoute
The example for the RouteObserver breaks at least with 2.12.0-beta and onward:

```
error: The argument type 'ModalRoute<Object?>' can't be assigned to the parameter type 'PageRoute<dynamic>'.
```

PageRoute is a child class of ModalRoute and assigning a ModalRoute to a PageRoute would require downcasting.

Inheritance:
```
Object Route<T> → OverlayRoute<T> → TransitionRoute<T> → ModalRoute<T> → PageRoute
```

The suggested fixes are

1) Change the type T in RouteObserver<T> from PageRoute to ModalRoute
2) Add a null check to ModalRoute.of(context)