Reverts "Roll Flutter Engine from 1cdbebee1901 to 45cf05f7a580 (10 revisions) (#149944)" (#149960)
Reverts: flutter/flutter#149944
Initiated by: jason-simmons
Reason for reverting: Regression affecting `integration_test/test/web_extension_test.dart`

```
  PathNotFoundException: Cannot open file, path = '/chromium/canvaskit.wasm' (OS Error: No such file or directory, errno = 2)
```

(see https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8745735238400976001/+/u/run_test.dart_for_web_long_running_tests_shard_and_subshard_1_5/stdout)

It looks like the p
Original PR Author: engine-flutter-autoroll

Reviewed By: {fluttergithubbot}

This change reverts the following previous change:

https://github.com/flutter/engine/compare/1cdbebee1901...45cf05f7a580

2024-06-07 yjbanov@google.com [web] add test for inefficient overlay allocation (flutter/engine#53284)
2024-06-07 jacksongardner@google.com Update Chrome to 125. (flutter/engine#53282)
2024-06-07 skia-flutter-autoroll@skia.org Roll Dart SDK from 4b693b16eec1 to d4f17e0bf28b (1 revision) (flutter/engine#53283)
2024-06-07 jacksongardner@google.com Fixes a few issues in flutter_js (flutter/engine#53231)
2024-06-07 skia-flutter-autoroll@skia.org Roll Fuchsia Linux SDK from aVohW_hnfDaE0smBX... to zpBZmUB_JC5AjG-f4... (flutter/engine#53279)
2024-06-07 skia-flutter-autoroll@skia.org Roll Dart SDK from 7b239d7f4578 to 4b693b16eec1 (1 revision) (flutter/engine#53277)
2024-06-07 skia-flutter-autoroll@skia.org Roll Skia from b7f51dfcc342 to ad3c9f203f4e (1 revision) (flutter/engine#53276)
2024-06-07 skia-flutter-autoroll@skia.org Roll Skia from 5fc83884a619 to b7f51dfcc342 (4 revisions) (flutter/engine#53275)
2024-06-07 jonahwilliams@google.com Revert "Widen CPU affinity set." (flutter/engine#53274)
2024-06-07 skia-flutter-autoroll@skia.org Roll Skia from e36110f8b451 to 5fc83884a619 (1 revision) (flutter/engine#53273)

Also rolling transitive DEPS:
  fuchsia/sdk/core/linux-amd64 from aVohW_hnfDaE to zpBZmUB_JC5A

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/flutter-engine-flutter-autoroll
Please CC matanl@google.com,rmistry@google.com,zra@google.com on the revert to ensure that a human
is aware of the problem.

To file a bug in Flutter: https://github.com/flutter/flutter/issues/new/choose

To report a problem with the AutoRoller itself, please file a bug:
https://issues.skia.org/issues/new?component=1389291&template=1850622

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md