Error in docs: `CustomPaint` instead of `CustomPainter`
Hi, while going through the code documentation of `CustomPainter`, I found an error in which `CustomPaint` was used instead of `CustomPainter`https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/custom_paint.dart#L29
Error: line 29: lib/src/rendering/custom_paint.dart

```
/// To implement a custom painter, either subclass or implement this interface
/// to define your custom paint delegate. [CustomPaint] subclasses must
/// implement the [paint] and [shouldRepaint] methods, and may optionally also...
```
Should be:
```
/// To implement a custom painter, either subclass or implement this interface
/// to define your custom paint delegate. [CustomPainter] subclasses must
/// implement the [paint] and [shouldRepaint] methods, and may optionally also...
```

This error is also available on the website docs https://api.flutter.dev/flutter/rendering/CustomPainter-class.html.